// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOiQqV6vUDoUYget1Gvr1BOA31-4C2V-o',
    appId: '1:678014410400:web:22737e4b8434d1f7af33c5',
    messagingSenderId: '678014410400',
    projectId: 'e-commerce-98189',
    authDomain: 'e-commerce-98189.firebaseapp.com',
    storageBucket: 'e-commerce-98189.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv6v9250gxWyQTcjOExGmaNh1HxzuLZU0',
    appId: '1:678014410400:android:c3370888e79032aaaf33c5',
    messagingSenderId: '678014410400',
    projectId: 'e-commerce-98189',
    storageBucket: 'e-commerce-98189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAem3dIe0F2lm3jVcR-Cfy9qmhns5yvVzc',
    appId: '1:678014410400:ios:67cc9e19fc628fc6af33c5',
    messagingSenderId: '678014410400',
    projectId: 'e-commerce-98189',
    storageBucket: 'e-commerce-98189.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAem3dIe0F2lm3jVcR-Cfy9qmhns5yvVzc',
    appId: '1:678014410400:ios:67cc9e19fc628fc6af33c5',
    messagingSenderId: '678014410400',
    projectId: 'e-commerce-98189',
    storageBucket: 'e-commerce-98189.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOiQqV6vUDoUYget1Gvr1BOA31-4C2V-o',
    appId: '1:678014410400:web:bd30e6045151b05baf33c5',
    messagingSenderId: '678014410400',
    projectId: 'e-commerce-98189',
    authDomain: 'e-commerce-98189.firebaseapp.com',
    storageBucket: 'e-commerce-98189.firebasestorage.app',
  );
}
